services:
    api:
        build:
            context: .
            dockerfile: docker/Dockerfile_api
        ports:
            - "4001:4001"   # [HOST_PORT]:[CONTAINER_PORT] ; HOST_PORT: port used to connect to API. CONTAINER_PORT: same value as "IN_PORT" below
            - "8008:8008"
        environment:
            - PELIAS_HOST=pelias_api:4000
            - PELIAS_ES_HOST=pelias_elasticsearch:9200
            - PELIAS_INTERPOL_HOST=pelias_interpolation:4300
            - LOG_LEVEL=LOW # LOW, MEDIUM or HIGH
            - NB_WORKERS=4  # Number of fastapi workers
            - IN_PORT=4001  # Internal port. Should correspond to the first value in the above "ports"
            - POSTCODE_MATCH_LENGTH=3  # Minimum number of characters to match a postcode, between input postcode and Pelias postcode. 4 = fully trust input postcode.
        networks:
            - belgium_bepelias_default
        volumes:
            - ./data/:/data/   # Only needs metadata.json, but if the file does not exist, it would be created as a directory
                               # if we tried to mount ./data/metadata.json:/data/metadata.json.
        image: bepelias/api
        container_name: bepelias_api
        restart: always

    dataprep:
        build:
            context: .
            dockerfile: docker/Dockerfile_dataprep
        volumes:
            - ./data:/data
        environment:
            - CHUNK_SIZE=100000  # Number of rows to process at once when preparing best files. If dataprep process runs out of memory, lower this value.
        image: bepelias/dataprep
        container_name: bepelias_dataprep

networks:
    belgium_bepelias_default:
        external: true
