FROM python:3.14-alpine

RUN apk add build-base gdal-dev geos-dev openjdk17

COPY best-tools-artifact/converter-*.jar /best-tools/java/

COPY docker/requirements_base.txt .

RUN python3 -m venv bepelias_venv
RUN bepelias_venv/bin/pip3 install -r requirements_base.txt

COPY scripts/Makefile /bepelias/Makefile
COPY src/bepelias/__init__.py src/bepelias/prepare_best_files.py /bepelias/
