FROM bepelias/base

RUN yum -y install maven java-17-openjdk git wget unzip yum-utils make jq && package-cleanup --leaves --all

RUN git clone --branch 1.5.0 https://github.com/Fedict/best-tools.git

WORKDIR /best-tools/java/

ENV JAVA_HOME="/usr/lib/jvm/jre-17/"

RUN mvn clean install -DskipTests

COPY ./scripts/Makefile /bepelias/Makefile
COPY src/bepelias/prepare_best_files.py src/bepelias/__init__.py /bepelias/